# 这是帮助您开始使用 Actions 的基本工作流程

名称：CI

# 运行时控制工作流
在：
  # 在个体或拉取请求事件上触发工作流程，但仅限于“master”分支# 在个体或拉取请求事件上触发工作流程，但仅限于“master”分支
  推：
    分支: [    分支：[ “主” ] “master”    ]
  拉请求：
    分支: [    分支：[ “主” ] “master”     ]

  # 允许您从“操作”选项卡手动运行此工作流程# 允许您从“操作”选项卡手动运行此工作流程
  工作流程_调度：

# 工作流程运行由一个或可以是顺序或任务运行的作业多个组成
工作：
  # 该工作流程包含一个名为“build”的作业#工作流程包含一个名为“build”的作业
  建造者：
    # 作业将运行的运行器类型# 作业将运行的运行器类型
    连续运行 :     运行：ubuntu-latest

    # 步骤表示将作为作业的一部分执行的一系列任务# 步骤表示将作为作业的一部分执行的一系列任务
    脚步：
      # 在$GITHUB_WORKSPACE下签出您的存储库，方便您的作业可以访问它
      -用途：actions/checkout@v3

      # 使用 runner shell 运行单个命令
      -姓名：运行脚本
        跑步：echo 你好，世界！

      # 使用 runner shell 运行一组命令
      -姓名：运行多行脚本
        运行：|
          echo 添加其他要构建的操作，
          echo 测试，并部署您的项目。
